
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author julien.belinga
 */
public class DistribFrame extends javax.swing.JFrame {

    private CDistributeur distrib;
    private CBoisson tabBoissons[] = new CBoisson[5];
    /**
     * Creates new form DistribFrame
     */
    public DistribFrame() {
        initComponents();
        CBoisson cafeCourt = new CBoisson("café court", 35, false, 5);
        CBoisson cafeLong = new CBoisson("café long", 35, false, 10);
        CBoisson chocolat = new CBoisson("chocolat chaud", 40, false, 10);
        CBoisson cappuccino = new CBoisson("cappuccino", 40, false, 10);
        CBoisson potageTomate = new CBoisson("potage tomate", 40, false, 10);
        
        tabBoissons[1] = cafeCourt;
        tabBoissons[2] = cafeLong;
        tabBoissons[3] = chocolat;
        tabBoissons[4] = cappuccino;
        tabBoissons[5] = potageTomate;
        
        distrib = new CDistributeur();
        
        distrib.ajouterBoisson(cafeCourt);
        //distrib.ajouterBoisson(cafeCourtSansSucre);
        distrib.ajouterBoisson(cafeLong);
        //distrib.ajouterBoisson(cafeLongSansSucre);
        distrib.ajouterBoisson(chocolat);
        distrib.ajouterBoisson(cappuccino);
        distrib.ajouterBoisson(potageTomate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSucreA = new javax.swing.JButton();
        jButtonSucreD = new javax.swing.JButton();
        jLabAffSucre = new javax.swing.JLabel();
        javax.swing.JButton jButB1 = new javax.swing.JButton();
        jButB2 = new javax.swing.JButton();
        jButB3 = new javax.swing.JButton();
        jButB4 = new javax.swing.JButton();
        jButB5 = new javax.swing.JButton();
        affBoisson = new javax.swing.JLabel();
        creditA = new javax.swing.JButton();
        creditD = new javax.swing.JButton();
        affCredit = new javax.swing.JLabel();
        jLabStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSucreA.setText("sucre +");
        jButtonSucreA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSucreAActionPerformed(evt);
            }
        });

        jButtonSucreD.setText("sucre -");
        jButtonSucreD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSucreDActionPerformed(evt);
            }
        });

        jLabAffSucre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabAffSucre.setText("sucre: 3");

        jButB1.setText("café court");
        jButB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButB1ActionPerformed(evt);
            }
        });

        jButB2.setText("café long");
        jButB2.setToolTipText("");
        jButB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButB2ActionPerformed(evt);
            }
        });

        jButB3.setText("chocolat");
        jButB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButB3ActionPerformed(evt);
            }
        });

        jButB4.setText("cappuccino");
        jButB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButB4ActionPerformed(evt);
            }
        });

        jButB5.setText("potage tomate");
        jButB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButB5ActionPerformed(evt);
            }
        });

        affBoisson.setText("selectionnez une boisson");
        affBoisson.setToolTipText("");

        creditA.setText("crédit +");
        creditA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditAActionPerformed(evt);
            }
        });

        creditD.setText("crédit -");
        creditD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditDActionPerformed(evt);
            }
        });

        affCredit.setText("insérer crédits");

        jLabStatus.setText("status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(creditD)
                        .addGap(18, 18, 18)
                        .addComponent(creditA)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButB5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButB4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(affBoisson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 107, Short.MAX_VALUE)
                                        .addComponent(jButtonSucreD)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonSucreA)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabAffSucre)
                                .addGap(55, 55, 55))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(affCredit)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButB2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(affBoisson, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButB3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButB4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButB5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabAffSucre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSucreA)
                            .addComponent(jButtonSucreD))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(affCredit)
                    .addComponent(jLabStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditA)
                    .addComponent(creditD))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSucreAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSucreAActionPerformed
        // TODO add your handling code here:
        distrib.augmenterSucre();
        jLabAffSucre.setText("sucre :" + MAJaff());
    }//GEN-LAST:event_jButtonSucreAActionPerformed

    private void jButtonSucreDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSucreDActionPerformed
        // TODO add your handling code here:
        distrib.diminuerSucre();
        jLabAffSucre.setText("sucre :" + MAJaff());
    }//GEN-LAST:event_jButtonSucreDActionPerformed

    private void creditAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditAActionPerformed
        // TODO add your handling code here:
        distrib.crediter(5);
        affCredit.setText("crédit :"+ MAJCredit());
    }//GEN-LAST:event_creditAActionPerformed

    private void creditDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditDActionPerformed
        // TODO add your handling code here:
        distrib.enleverCredit(5);
        affCredit.setText("crédit :" + MAJCredit());
    }//GEN-LAST:event_creditDActionPerformed

    private void jButB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButB1ActionPerformed
        // TODO add your handling code here:
        CBoisson actuel;
        actuel = tabBoissons[1];
        
        try {
            retraitCredit(actuel);
        } catch (InterruptedException ex) {
            Logger.getLogger(DistribFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButB1ActionPerformed

    private void jButB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButB2ActionPerformed
        // TODO add your handling code here:
        CBoisson actuel;
        actuel = tabBoissons[2];
        
        try {
            retraitCredit(actuel);
        } catch (InterruptedException ex) {
            Logger.getLogger(DistribFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButB2ActionPerformed

    private void jButB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButB3ActionPerformed
        // TODO add your handling code here:
        CBoisson actuel;
        actuel = tabBoissons[3];
        
        try {
            retraitCredit(actuel);
        } catch (InterruptedException ex) {
            Logger.getLogger(DistribFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButB3ActionPerformed

    private void jButB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButB4ActionPerformed
        // TODO add your handling code here:
        CBoisson actuel;
        actuel = tabBoissons[4];
        
        try {
            retraitCredit(actuel);
        } catch (InterruptedException ex) {
            Logger.getLogger(DistribFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButB4ActionPerformed

    private void jButB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButB5ActionPerformed
        // TODO add your handling code here:
        CBoisson actuel;
        actuel = tabBoissons[5];
        
        try {
            retraitCredit(actuel);
        } catch (InterruptedException ex) {
            Logger.getLogger(DistribFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButB5ActionPerformed
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistribFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistribFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistribFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistribFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DistribFrame().setVisible(true);
            }
        });
    }
    
    private int MAJaff(){
        distrib.getSucre();
                return distrib.getSucre();
    }
    
    private int MAJCredit(){
        distrib.getCredit();
                return distrib.getCredit();
    }
    
    private int retraitCredit(CBoisson a) throws InterruptedException{
        if(distrib.getCredit() < a.getPrix())
            jLabAffSucre.setText("crédit insufisant");
        else{
            
            for(int i = a.getPrix(); i > 0; i = distrib.getCredit()){
                distrib.enleverCredit(5);
            }
            
            affBoisson.setText(a.getNom()+" en préparation...");
            affBoisson.setText("" + a.getNom());
            jLabStatus.setText("le gobelet tombe");
            for (int k = 0; k < a.getQte(); k++){
                Thread.sleep(200);
                jLabStatus.setText(k + " cl");
            }
            jLabStatus.setText("récupérer votre boisson!");
            
            if(distrib.getCredit() > 0){
            while(distrib.getCredit() > 0){
                distrib.enleverCredit(5);
            }
            jLabStatus.setText("récupérer votre monaie");
            }
        }
            
            return distrib.getCredit();
    }
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel affBoisson;
    private javax.swing.JLabel affCredit;
    private javax.swing.JButton creditA;
    private javax.swing.JButton creditD;
    private javax.swing.JButton jButB2;
    private javax.swing.JButton jButB3;
    private javax.swing.JButton jButB4;
    private javax.swing.JButton jButB5;
    private javax.swing.JButton jButtonSucreA;
    private javax.swing.JButton jButtonSucreD;
    private javax.swing.JLabel jLabAffSucre;
    private javax.swing.JLabel jLabStatus;
    // End of variables declaration//GEN-END:variables
}
